



DROP DATABASE IF EXISTS MyPapyrus;

Create database MyPapyrus;



DROP TABLE IF EXISTS Produit ;


CREATE TABLE Produit (
  CODART INT NOT NULL,
  LIBART VARCHAR(45) NULL,
  STKLE VARCHAR(45) NULL,
  QTEANN INT NULL,
  UNIMES VARCHAR(45) NULL,
  PRIMARY KEY (CODART))


DROP TABLE IF EXISTS Fournis ;

CREATE TABLE Fournis (
  NUMFOU INT NOT NULL,
  NOUFOU VARCHAR(45) NULL,
  RUEFOU VARCHAR(45) NULL,
  POSFOU VARCHAR(45) NULL,
  VILFOU VARCHAR(45) NULL,
  CONFOU VARCHAR(45) NULL,
  SATISF VARCHAR(45) NULL,
  PRIMARY KEY (NUMFOU));





CREATE TABLE Vente (
  CODART INT PRIMARY KEY NOT NULL,
  NUMFOU INT PRIMARY KEY NOT NULL,
  DELLIV VARCHAR(45) NULL,
  QTE1 INT NULL,
  PRIX1 DECIMAL(15) NULL,
  QTE2 INT NULL,
  PRIX2 DECIMAL(15) NULL,
  QTE2 INT NULL,
  PRIX2 DECIMAL(15) NULL,
  QTE3 INT NULL,
  PRIX3 DECIMAL(15) NULL,
    FOREIGN KEY (CODART) REFERENCES Produit(CODART),
    FOREIGN KEY (NUMFOU) REFERENCES Fournis(NUMFOU))

 
DROP TABLE IF EXISTS ENTCOM ;

CREATE TABLE ENTCOM (
  NUMCOM INT NOT NULL,
  OBSCOM VARCHAR(45) NULL,
  DATCOM DATETIME NULL,
  NUMFOU INT NULL,
  PRIMARY KEY (NUMCOM),
  FOREIGN KEY (NUMFOU) REFERENCES Fournis(NUMFOU))



DROP TABLE IF EXISTS LIGCOM ;

CREATE TABLE LIGCOM (
  NUMCOM INT NOT NULL,
  NUMLIG INT NOT NULL,
  CODART INT NULL,
  QTECDE INT NULL,
  PRIUNI DECIMAL(15) NULL,
  QTELIV INT NULL,
  DERLIV VARCHAR(45) NULL,
  PRIMARY KEY (NUMCOM, NUMLIG),
  FOREIGN KEY (NUMCOM) REFERENCES Entcom(NUMCOM),
  FOREIGN KEY (CODART) REFERENCES Produit(CODART))
  



